# Generated by Django 5.1.1 on 2024-10-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportafolio', '0003_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulacion', models.TextField(blank=True, null=True, verbose_name='Titulo')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('nota_media', models.IntegerField(blank=True, null=True, verbose_name='Nota Media')),
                ('lugarEstudio', models.TextField(blank=True, null=True, verbose_name='Lugar Estudio')),
                ('nombreLugar', models.TextField(blank=True, null=True, verbose_name='Nombre Lugar')),
                ('ciudad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Ciudad')),
                ('presencial', models.BooleanField(default=False, verbose_name='Presencial')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
