# Generated by Django 5.1.1 on 2024-10-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appportafolio', '0004_estudios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudios',
            new_name='Estudio',
        ),
        migrations.AlterModelOptions(
            name='estudio',
            options={'ordering': ['titulacion'], 'verbose_name': 'Estudio', 'verbose_name_plural': 'Estudios'},
        ),
    ]
