# Generated by Django 3.2 on 2024-11-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportafolio', '0007_auto_20241031_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('comentario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('comentario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['id'],
            },
        ),
    ]
