# Generated by Django 3.2 on 2024-11-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appportafolio', '0008_imagen_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='appportafolio.personal')),
            ],
            options={
                'verbose_name': 'curriculum',
                'verbose_name_plural': 'curriculums',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCurriculumExperiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appportafolio.curriculum')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appportafolio.experiencia')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCurriculumEstudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appportafolio.curriculum')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appportafolio.estudio')),
            ],
        ),
    ]
