# Generated by Django 3.2 on 2024-11-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appportafolio', '0009_curriculum_detallecurriculumestudio_detallecurriculumexperiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='detallecurriculumestudio',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_curriculums', to='appportafolio.estudio'),
        ),
    ]
