# Generated by Django 3.2 on 2024-12-06 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appportafolio', '0015_rename_estado_tarea_fkestado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['fecha_tarea'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha',
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_tarea',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de envio'),
        ),
    ]
